name = "nada_mental_health"
version = "0.1.0"
authors = [""]

[[programs]]
path = "src/secret_addition.py"
name = "secret_addition"
prime_size = 128

[[programs]]
path = "src/mental_main.py"
name = "mental_main"
prime_size = 128